"""
Summarization Module - Uses Ollama for local LLM-based meeting summarization.
"""
import json
import requests


class Summarizer:
    def __init__(self, ollama_url="http://localhost:11434", model="llama3.2"):
        """
        Initialize the summarizer.

        Args:
            ollama_url: URL where Ollama is running
            model: Ollama model to use. Good options:
                   - "llama3.2" (3B, fast, good quality)
                   - "llama3.1" (8B, better quality)
                   - "mistral" (7B, good for summarization)
                   - "phi3" (3.8B, fast and capable)
        """
        self.ollama_url = ollama_url.rstrip("/")
        self.model = model

    def check_ollama(self):
        """Check if Ollama is running and the model is available."""
        try:
            resp = requests.get(f"{self.ollama_url}/api/tags", timeout=5)
            if resp.status_code != 200:
                return False, "Ollama is not responding correctly."

            models = [m["name"].split(":")[0] for m in resp.json().get("models", [])]
            if self.model not in models:
                return (
                    False,
                    f"Model '{self.model}' not found. Available: {', '.join(models) or 'none'}.\n"
                    f"Run: ollama pull {self.model}",
                )
            return True, "Ollama is ready."
        except requests.ConnectionError:
            return False, "Cannot connect to Ollama. Make sure it's running (ollama serve)."
        except Exception as e:
            return False, f"Error checking Ollama: {e}"

    def summarize(self, transcript, progress_callback=None):
        """
        Summarize a meeting transcript using the local LLM.

        Args:
            transcript: The full meeting transcript text
            progress_callback: Optional callback for progress updates

        Returns:
            dict with 'summary', 'action_items', and 'key_points'
        """
        if progress_callback:
            progress_callback("Generating meeting summary with AI...")

        prompt = f"""You are a meeting summarization assistant. Analyze the following meeting transcript and provide:

1. **SUMMARY**: A concise 3-5 paragraph summary of the meeting, covering the main topics discussed.

2. **KEY POINTS**: A bullet-point list of the most important points and decisions made.

3. **ACTION ITEMS**: A bullet-point list of any tasks, follow-ups, or action items mentioned, with who is responsible if stated.

4. **TOPICS DISCUSSED**: A brief list of main topics/themes covered.

Please be thorough but concise. Format your response clearly with the section headers above.

--- TRANSCRIPT ---
{transcript[:15000]}
--- END TRANSCRIPT ---

Please provide your analysis:"""

        try:
            resp = requests.post(
                f"{self.ollama_url}/api/generate",
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.3,
                        "num_predict": 2048,
                    },
                },
                timeout=300,
            )

            if resp.status_code != 200:
                raise RuntimeError(f"Ollama returned status {resp.status_code}: {resp.text}")

            result = resp.json()
            summary_text = result.get("response", "")

            if progress_callback:
                progress_callback("Summary generated successfully.")

            return {
                "summary": summary_text,
                "model_used": self.model,
                "tokens_generated": result.get("eval_count", 0),
            }

        except requests.Timeout:
            raise RuntimeError(
                "Ollama timed out. The transcript may be too long, or the model is still loading."
            )
        except requests.ConnectionError:
            raise RuntimeError(
                "Lost connection to Ollama. Make sure it's still running."
            )

    def save_summary(self, summary_result, transcript_result, output_path):
        """Save the summary to a file."""
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("=" * 60 + "\n")
            f.write("MEETING SUMMARY\n")
            f.write(f"Generated by: {summary_result['model_used']} (local)\n")
            if transcript_result:
                f.write(
                    f"Meeting Duration: {transcript_result['duration']:.0f} seconds\n"
                )
            f.write("=" * 60 + "\n\n")
            f.write(summary_result["summary"])
            f.write("\n")

        return output_path
