/**
 * Rate Upload Service
 * ────────────────────
 * Pure logic for the "Upload Rates (Excel)" flow on RateManagementPage.
 * Owns header-mapping, row normalization, per-row validation, and chunked
 * persistence so the modal stays a thin presentational layer
 * (CLAUDE_RULES §2 — services-first; §6/§9 — no large inline blocks; §10 —
 * no hardcoded data in UI).
 *
 * The upload format mirrors the CSV/XLSX template generated by
 * rateService.downloadRateTemplate() so a "download → fill in → upload"
 * round-trip is the supported workflow. Header matching is intentionally
 * permissive (case + whitespace insensitive, accepts a handful of common
 * aliases) so a re-saved Excel file with slightly mangled headers still
 * imports cleanly.
 *
 * The DB write shape is the same one EditRateModal.buildPayload produces,
 * so both single-edit and bulk-import land identical column values.
 */

import * as XLSX from "xlsx";
import { DbApi } from "../lib/api";
import { normalizeMatchType } from "./rateService";

/* ─────────────────────────────────────────────────────────────
 * Header → DB column mapping
 *
 * Each entry lists the canonical template header plus the aliases
 * we accept (lower-cased, punctuation-stripped). Keep this list in
 * sync with RATE_TEMPLATE_COLUMNS in rateService.js.
 * ───────────────────────────────────────────────────────────── */
const HEADER_ALIASES = {
  lane:            ["lane id", "lane", "lane_id", "laneid"],
  match_type:      ["match type", "match_type", "matchtype"],
  origin_city:     ["origin city", "origin_city", "origincity", "from city"],
  origin_state:    ["origin state", "origin_state", "originstate"],
  origin_zip:      ["origin zip", "origin_zip", "originzip", "origin postcode"],
  origin_country:  ["origin country", "origin_country", "origincountry"],
  dest_city:       ["destination city", "dest city", "dest_city", "destcity", "to city"],
  dest_state:      ["destination state", "dest state", "dest_state", "deststate"],
  dest_zip:        ["destination zip", "dest zip", "dest_zip", "destzip"],
  dest_country:    ["destination country", "dest country", "dest_country", "destcountry"],
  carrier:         ["carrier", "carrier name"],
  mode:            ["mode", "transport mode"],
  rate:            ["rate", "rate amount", "rate ($)"],
  unit:            ["rate unit", "unit"],
  fsc:             ["fsc %", "fsc", "fsc_pct", "fuel surcharge"],
  discount:        ["discount %", "discount", "discount_pct"],
  discount_flat:   ["discount $ (flat)", "discount $", "discount flat", "discount_flat", "discount_amt"],
  eff:             ["effective date", "effective", "eff", "effective_date"],
  exp:             ["expiry date", "expires", "exp", "expiry_date", "expiration date"],
  status:          ["status"],
  service_level:   ["service level", "service_level", "service"],
  transit_days:    ["transit days", "transit_days", "transit"],
  miles:           ["miles", "distance"],
  czarlite:        ["czarlite (y/n)", "czarlite", "is czarlite"],
  czarlite_class:  ["czarlite freight class", "czarlite class", "czarlite_class", "freight class"],
};

const REQUIRED_FIELDS = ["lane", "carrier", "mode", "origin_city", "dest_city", "rate"];
const VALID_MODES   = ["TL", "LTL", "Intermodal", "Flatbed", "Reefer", "Air Freight", "Parcel"];
const VALID_STATUS  = ["Active", "Expiring", "Expired", "Pending", "Expiring Soon"];
const VALID_UNITS   = ["per mile", "per cwt", "flat", "container"];

/** Lower-cased + trimmed + collapse-whitespace key for header lookup. */
function normalizeHeaderKey(s) {
  return String(s || "").toLowerCase().replace(/\s+/g, " ").trim();
}

/**
 * Build a `header(text) → canonical(field)` map for the supplied
 * spreadsheet headers, given the alias dictionary above. Headers that
 * don't match anything are mapped to `null` so the caller can warn the
 * user about ignored columns instead of silently dropping data.
 */
export function mapHeaders(headers) {
  const map = {};
  for (const raw of headers || []) {
    const key = normalizeHeaderKey(raw);
    let matched = null;
    for (const [canonical, aliases] of Object.entries(HEADER_ALIASES)) {
      if (aliases.includes(key)) { matched = canonical; break; }
    }
    map[raw] = matched;
  }
  return map;
}

/**
 * Parse a File or Blob (CSV / XLSX / XLSM / XLS) into a list of
 * header-keyed plain objects. The first sheet is read; empty rows are
 * dropped. Dates come back as strings in `YYYY-MM-DD` form so the
 * downstream payload doesn't have to deal with Excel's serial-day numbers.
 *
 * @returns {Promise<{ headers: string[], rows: Object[] }>}
 */
export async function parseRateFile(file) {
  if (!file) throw new Error("parseRateFile: file is required");
  const buffer = await file.arrayBuffer();
  const wb = XLSX.read(buffer, { type: "array", cellDates: true });
  const sheetName = wb.SheetNames[0];
  if (!sheetName) throw new Error("Workbook contains no sheets");
  const sheet = wb.Sheets[sheetName];
  // header:1 → array-of-arrays so we can capture the original header row
  // verbatim (including casing/spacing) for `mapHeaders`.
  const aoa = XLSX.utils.sheet_to_json(sheet, { header: 1, raw: false, defval: "" });
  if (!aoa.length) return { headers: [], rows: [] };
  const headers = (aoa[0] || []).map((h) => String(h || "").trim());
  const rows = [];
  for (let i = 1; i < aoa.length; i++) {
    const row = aoa[i];
    if (!row || row.every((c) => c === "" || c == null)) continue;
    const obj = {};
    headers.forEach((h, idx) => { obj[h] = row[idx] !== undefined ? row[idx] : ""; });
    rows.push(obj);
  }
  return { headers, rows };
}

/* ─────────────────────────────────────────────────────────────
 * Cell-value normalizers
 * ───────────────────────────────────────────────────────────── */

function toNumberOrNull(v) {
  if (v === "" || v == null) return null;
  const n = typeof v === "number" ? v : parseFloat(String(v).replace(/[$,%\s]/g, ""));
  return Number.isFinite(n) ? n : null;
}

function toIsoDateOrNull(v) {
  if (v === "" || v == null) return null;
  if (v instanceof Date && !isNaN(v.getTime())) return v.toISOString().slice(0, 10);
  const s = String(v).trim();
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
  // Try US-style M/D/YYYY → ISO
  const m = s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})$/);
  if (m) {
    let [, mo, da, yr] = m;
    if (yr.length === 2) yr = (parseInt(yr, 10) >= 70 ? "19" : "20") + yr;
    return `${yr}-${mo.padStart(2, "0")}-${da.padStart(2, "0")}`;
  }
  const d = new Date(s);
  if (!isNaN(d.getTime())) return d.toISOString().slice(0, 10);
  return null;
}

function toBool(v) {
  if (v === true) return true;
  if (v === false || v == null || v === "") return false;
  const s = String(v).trim().toLowerCase();
  return s === "y" || s === "yes" || s === "true" || s === "1";
}

function normalizeUnit(raw) {
  if (!raw) return "per mile";
  const u = String(raw).toLowerCase().trim();
  if (u.includes("mile")) return "per mile";
  if (u.includes("cwt")) return "per cwt";
  if (u === "flat" || u.includes("flat")) return "flat";
  if (u.includes("container")) return "container";
  return "per mile";
}

function buildLocationString(city, state, zip) {
  const parts = [];
  if (city) parts.push(String(city).trim());
  if (state) parts.push(String(state).trim().toUpperCase());
  let s = parts.join(", ");
  if (zip) s = (s ? s + " " : "") + String(zip).trim();
  return s;
}

/* ─────────────────────────────────────────────────────────────
 * Row → DB-payload normalization
 * ───────────────────────────────────────────────────────────── */

/**
 * Convert one header-keyed raw row (as produced by `parseRateFile`) into
 * the same payload shape EditRateModal.buildPayload writes. Pure — no IO.
 *
 * `headerMap` is the dictionary returned from `mapHeaders`.
 */
export function normalizeUploadedRow(rawRow, headerMap) {
  // Project the row through the canonical-field map.
  const f = {};
  for (const [hdr, canonical] of Object.entries(headerMap)) {
    if (!canonical) continue;
    const val = rawRow[hdr];
    if (val === undefined) continue;
    f[canonical] = typeof val === "string" ? val.trim() : val;
  }

  const lane = String(f.lane || "").trim();
  const mode = String(f.mode || "TL").trim();

  const origin = buildLocationString(f.origin_city, f.origin_state, f.origin_zip);
  const dest   = buildLocationString(f.dest_city,   f.dest_state,   f.dest_zip);

  const rateNum = toNumberOrNull(f.rate);
  const fscNum  = toNumberOrNull(f.fsc);
  const cz      = toBool(f.czarlite);

  return {
    lane,
    mode,
    match_type:     normalizeMatchType(f.match_type),
    origin_zip:     f.origin_zip ? String(f.origin_zip).trim() : null,
    dest_zip:       f.dest_zip   ? String(f.dest_zip).trim()   : null,
    origin_country: String(f.origin_country || "USA").toUpperCase(),
    dest_country:   String(f.dest_country   || "USA").toUpperCase(),
    origin,
    dest,
    carrier: String(f.carrier || "").trim(),
    status:  String(f.status || "Active").trim() || "Active",
    rate:    rateNum != null ? `$${rateNum.toFixed(2)}` : "",
    unit:    normalizeUnit(f.unit),
    fsc:     fscNum != null ? `${fscNum.toFixed(1)}%` : "",
    discount:      toNumberOrNull(f.discount),
    discount_flat: toNumberOrNull(f.discount_flat),
    eff: toIsoDateOrNull(f.eff),
    exp: toIsoDateOrNull(f.exp),
    miles:        toNumberOrNull(f.miles),
    transit_days: toNumberOrNull(f.transit_days),
    service_level: f.service_level ? String(f.service_level).trim() : null,
    czarlite: cz,
    czarlite_class:  toNumberOrNull(f.czarlite_class),
  };
}

/* ─────────────────────────────────────────────────────────────
 * Per-row validation
 * ───────────────────────────────────────────────────────────── */

/**
 * Validate the *raw* (header-keyed) row plus its normalized payload.
 * Returns `{ ok, errors[] }` where `errors` describe the user-visible
 * problems with that row. Empty `errors` ⇒ row is safe to upsert.
 */
export function validateRateRow(rawRow, headerMap, payload) {
  const errors = [];

  // Required fields — check both raw (so the user sees "Carrier missing"
  // instead of "carrier ''") and normalized.
  for (const field of REQUIRED_FIELDS) {
    const headerEntry = Object.entries(headerMap).find(([, c]) => c === field);
    const headerName = headerEntry ? headerEntry[0] : field;
    const raw = headerEntry ? rawRow[headerEntry[0]] : null;
    const present = raw !== undefined && raw !== null && String(raw).trim() !== "";
    if (!present) errors.push(`${headerName} is required`);
  }

  if (payload.mode && !VALID_MODES.includes(payload.mode)) {
    errors.push(`Mode "${payload.mode}" is not one of: ${VALID_MODES.join(", ")}`);
  }
  if (payload.status && !VALID_STATUS.includes(payload.status)) {
    errors.push(`Status "${payload.status}" is not one of: ${VALID_STATUS.join(", ")}`);
  }
  if (payload.unit && !VALID_UNITS.includes(payload.unit)) {
    errors.push(`Rate Unit "${payload.unit}" is not one of: ${VALID_UNITS.join(", ")}`);
  }
  if (payload.eff && payload.exp && payload.eff > payload.exp) {
    errors.push("Effective Date must be on or before Expiry Date");
  }
  // ZIP-to-zip rows must carry both ZIPs.
  if (payload.match_type === "zip_to_zip") {
    if (!payload.origin_zip) errors.push("Origin ZIP is required for zip_to_zip rates");
    if (!payload.dest_zip)   errors.push("Destination ZIP is required for zip_to_zip rates");
  }

  return { ok: errors.length === 0, errors };
}

/* ─────────────────────────────────────────────────────────────
 * Top-level analysis used by the modal
 * ───────────────────────────────────────────────────────────── */

/**
 * Analyze the parsed rows against the supplied header map and the
 * caller's existing-lanes set. Returns a summary the modal renders
 * directly:
 *
 *   {
 *     headerMap,
 *     unmappedHeaders: string[],                 // headers we'll ignore
 *     analyzed: Array<{
 *       rowNumber,                               // 1-based excluding header
 *       raw:    Object,                          // header-keyed raw row
 *       payload: Object,                         // normalized DB row
 *       errors: string[],                        // validation issues
 *       conflict: boolean,                       // lane already exists
 *       existingId: string|null,                 // id of the existing rate (for overwrite)
 *     }>,
 *     counts: { total, valid, invalid, conflicts, newRows },
 *   }
 */
export function analyzeRateUpload({ headers, rows, existingRates = [] }) {
  const headerMap = mapHeaders(headers);
  const unmappedHeaders = Object.entries(headerMap)
    .filter(([, c]) => !c)
    .map(([h]) => h)
    .filter(Boolean);

  // O(1) existing-lane lookup, case-insensitive.
  const lanesIndex = new Map();
  for (const r of existingRates || []) {
    if (r?.lane) lanesIndex.set(String(r.lane).toLowerCase(), r);
  }

  const analyzed = rows.map((raw, i) => {
    const payload = normalizeUploadedRow(raw, headerMap);
    const { errors } = validateRateRow(raw, headerMap, payload);
    const existing = payload.lane ? lanesIndex.get(payload.lane.toLowerCase()) : null;
    return {
      rowNumber: i + 2, // +1 for 1-based, +1 for the header row
      raw,
      payload,
      errors,
      conflict:   !!existing,
      existingId: existing?.id || null,
    };
  });

  const counts = {
    total:     analyzed.length,
    valid:     analyzed.filter((a) => a.errors.length === 0).length,
    invalid:   analyzed.filter((a) => a.errors.length  >  0).length,
    conflicts: analyzed.filter((a) => a.conflict).length,
    newRows:   analyzed.filter((a) => !a.conflict).length,
  };

  return { headerMap, unmappedHeaders, analyzed, counts };
}

/* ─────────────────────────────────────────────────────────────
 * Bulk upsert
 * ───────────────────────────────────────────────────────────── */

/**
 * Persist a list of analyzed rows. Conflict mode controls how we treat
 * rows whose `lane` already exists in the DB:
 *
 *   "skip"      → ignore conflicting rows entirely (default)
 *   "overwrite" → PATCH the existing row by id
 *
 * Reports progress via `onProgress({ completed, total })` after each row
 * so the modal can render a progress bar without polling. Returns a
 * summary `{ inserted, updated, skipped, failed: [{ rowNumber, lane, error }] }`.
 *
 * The function is intentionally per-row rather than batched: the existing
 * `/api/db/:table` endpoint operates on one row at a time, and small N
 * (typical rate sheets are <1000 rows) keeps this acceptable while giving
 * us stable per-row error reporting. If row counts grow, swap this for a
 * dedicated bulk endpoint and keep the same callsite contract.
 */
export async function bulkUpsertRates(analyzed, {
  conflictMode = "skip",
  onProgress = null,
} = {}) {
  const out = { inserted: 0, updated: 0, skipped: 0, failed: [] };
  // Defensive: drop rows with errors here too — UI should already filter
  // them, but services own the contract (CLAUDE_RULES §4).
  const queue = (analyzed || []).filter((a) => a.errors.length === 0);
  const total = queue.length;

  for (let i = 0; i < queue.length; i++) {
    const item = queue[i];
    try {
      if (item.conflict) {
        if (conflictMode === "overwrite" && item.existingId) {
          await DbApi.patch("rates", item.existingId, item.payload);
          out.updated++;
        } else {
          out.skipped++;
        }
      } else {
        await DbApi.upsert("rates", item.payload);
        out.inserted++;
      }
    } catch (err) {
      out.failed.push({
        rowNumber: item.rowNumber,
        lane: item.payload?.lane || "",
        error: err?.message || String(err),
      });
    }
    if (onProgress) onProgress({ completed: i + 1, total });
  }

  return out;
}
